# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soyzniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_image', models.ImageField(upload_to=news.models.Images.path_upload, verbose_name='Изображение')),
                ('prev_image', models.CharField(blank=True, default='', max_length=255, verbose_name='Уменьшеная копия')),
                ('name', models.CharField(blank=True, default='Image', max_length=255, verbose_name='Название изображения')),
                ('priority', models.IntegerField(blank=True, default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name_plural': 'Изображения',
                'db_table': 'news_images',
                'verbose_name': 'Изображение',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='заголовок новсти')),
                ('content', models.TextField(verbose_name='содержание новости')),
                ('date_pub', models.DateField(default=datetime.date(2017, 9, 25))),
                ('link', models.CharField(max_length=160, unique=True, verbose_name='ссылка на новость')),
                ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='источник')),
                ('link_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на источник')),
                ('link_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на видео youtube')),
                ('online', models.BooleanField(default=False, verbose_name='На сайте')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_rubric', to='soyzniki.Country', verbose_name='страна')),
                ('image', models.ManyToManyField(to='news.Images', verbose_name='изображения')),
            ],
            options={
                'verbose_name_plural': 'новсти',
                'db_table': 'news',
                'verbose_name': 'новость',
                'ordering': ['-date_pub', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=50, verbose_name='название рубрики')),
                ('name_en', models.CharField(max_length=50, verbose_name='название на латинице')),
                ('active', models.BooleanField(default=False, verbose_name='На сайте')),
            ],
            options={
                'verbose_name_plural': 'рубрики',
                'db_table': 'rubric',
                'verbose_name': 'рубрика',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Rubric', verbose_name='рубрика'),
        ),
    ]
