# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170930_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_pub',
            field=models.DateField(default=datetime.date(2017, 10, 3)),
        ),
    ]
