# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=30, unique=True, verbose_name='Название услуги РУС')),
                ('name_en', models.CharField(max_length=30, verbose_name='Название услуги ENG')),
                ('icon', models.FileField(upload_to=map.models.Services.get_icon_path, verbose_name='Иконка сервиса (svg)')),
                ('mark', models.FileField(upload_to=map.models.Services.get_mark_path, verbose_name='Маркер сервиса (svg)')),
                ('desc', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('active', models.BooleanField(default=True, verbose_name='Включиь в поиск')),
            ],
            options={
                'verbose_name_plural': 'Сервисы',
                'db_table': 'services',
                'verbose_name': 'Сервис',
                'ordering': ['-priority'],
            },
        ),
    ]
