# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import soyzniki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, verbose_name='Англоязычное название')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Рускоязычное название')),
                ('capital', models.BooleanField(default=False, verbose_name='Столица государства (да/нет)')),
                ('latitude', models.CharField(default='', max_length=10, verbose_name='Широта цетральной точки города')),
                ('longitude', models.CharField(default='', max_length=10, verbose_name='Долгота центральной точки города')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'verbose_name': 'Город',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Англоязычное название')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Рускоязычное название')),
                ('double_code', models.CharField(default='', max_length=3, verbose_name='Двухзначный код')),
                ('border', models.FileField(default='none', upload_to=soyzniki.models.Country.get_image_path, verbose_name='Картинка страны')),
                ('active', models.BooleanField(verbose_name='Включена в поиск')),
                ('latitude', models.CharField(default='', max_length=10, verbose_name='Широта цетральной точки страны')),
                ('longitude', models.CharField(default='', max_length=10, verbose_name='Долгота центральной точки страны')),
            ],
            options={
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
                'verbose_name': 'Страна',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, verbose_name='Англоязычное название')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Рускоязычное название')),
                ('latitude', models.CharField(default='', max_length=10, verbose_name='Широта цетральной точки района')),
                ('longitude', models.CharField(default='', max_length=10, verbose_name='Долгота центральной точки района')),
            ],
            options={
                'verbose_name_plural': 'Районы',
                'db_table': 'districts',
                'verbose_name': 'Район',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_ip', models.CharField(max_length=115, verbose_name='Начало диапазона IP')),
                ('end_ip', models.CharField(max_length=15, verbose_name='Конец диапазона IP')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_country', to='soyzniki.Country', verbose_name='Страна, которой принадлежит IP')),
            ],
            options={
                'verbose_name_plural': 'Диапазоны IP',
                'db_table': 'ip_country',
                'verbose_name': 'Диапазон IP',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, verbose_name='Англоязычное название')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Рускоязычное название')),
                ('latitude', models.CharField(default='', max_length=10, verbose_name='Широта цетральной точки региона')),
                ('longitude', models.CharField(default='', max_length=10, verbose_name='Долгота центральной точки региона')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_counrty', to='soyzniki.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'verbose_name': 'Регион',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_timezone', models.CharField(max_length=23, verbose_name='Название временной зоны')),
                ('offset_time', models.CharField(max_length=6, verbose_name='Смещение относительно Гринвича')),
            ],
            options={
                'verbose_name_plural': 'Временные зоны',
                'db_table': 'timezone',
                'verbose_name': 'Временная зона',
            },
        ),
        migrations.AddField(
            model_name='ip',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.Timezone', verbose_name='Временная зона'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_region', to='soyzniki.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='soyzniki.Country', verbose_name='Сталица какого государства'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_district', to='soyzniki.District', verbose_name='Район'),
        ),
    ]
