# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soyzniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='soyzniki.Country', verbose_name='Сталица какого государства'),
        ),
    ]
