from django.conf.urls import url
from partner import views


urlpatterns = [
    url(r'^all/$',
        views.all, name='all'),
    url(r'^add/$',
        views.add, name='add'),
    url(r'^(?P<unp_unn>[\d]+)/$',
        views.parther_page, name='parther_page'),
    url(r'^(?P<unp_unn>[\d]+)/edit/$',
        views.edit, name='edit'),
    url(r'^(?P<unp_unn>[\d]+)/admin/$',
        views.admin, name='admin'),
    url(r'^(?P<unp_unn>[\d]+)/delete/$',
        views.delete, name='delete'),
    url(r'^point/(?P<id_point>[\d]+)/$',
        views.point_view, name='point_view'),
    url(r'^(?P<unp_unn>[\d]+)/points/all/(?P<page>[\d]+)/$',
        views.points, name='points'),
    url(r'^(?P<unp_unn>[\d]+)/points/servis/(?P<servis>[\w]+)/(?P<page>[\d]+)/$',
        views.point_filter_servis, name='point_filter_servis'),
    url(r'^(?P<unp_unn>[\d]+)/points/country/(?P<country>[\w]+)/(?P<page>[\d]+)/$',
        views.point_filter_country, name='point_filter_country'),
    url(r'^(?P<unp_unn>[\d]+)/points/region/(?P<region>[\w]+)/(?P<page>[\d]+)/$',
        views.point_filter_region, name='point_filter_region'),
    url(r'^(?P<unp_unn>[\d]+)/point/add/$',
        views.point_add, name='point_add'),
    url(r'^(?P<unp_unn>[\d]+)/point/(?P<id_point>[\d]+)/edit/$',
        views.point_edit, name='point_edit'),
    url(r'^(?P<unp_unn>[\d]+)/point/(?P<id_point>[\d]+)/delete/$',
        views.point_delete, name='point_delete'),
    url(r'^(?P<unp_unn>[\d]+)/point/(?P<id_point>[\d]+)/hide/$',
        views.point_hide, name='point_hide'),
    url(r'^(?P<unp_unn>[\d]+)/point/(?P<id_point>[\d]+)/visible/$',
        views.point_visible, name='point_visible'),
    url(r'^(?P<unp_unn>[\d]+)/(?P<login>[\w]+)/delete/$',
        views.delete_admin, name='delete_admin'),
]
