# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applications', models.CharField(max_length=50, verbose_name='Приложение')),
                ('model', models.CharField(max_length=50, verbose_name='Модель приложения')),
                ('record_id', models.IntegerField(verbose_name='Id записи')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок коментария')),
                ('comment', models.TextField(max_length=1000, verbose_name='Коментарий')),
                ('date_add', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 26, 16, 4, 18, 738513), verbose_name='Дата и время добавления')),
                ('priority', models.IntegerField(blank=True, default=0, verbose_name='Проритет записи')),
                ('moderation', models.BooleanField(default=False, verbose_name='Проверка пройдена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'db_table': 'comments',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-priority', '-date_add'],
            },
        ),
    ]
