# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 13, 11, 9, 9, 525971), verbose_name='Дата и время добавления'),
        ),
    ]
