# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 30, 0, 19, 48, 519421), verbose_name='Дата и время добавления'),
        ),
    ]
