# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170713_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 21, 15, 41, 57, 416208), verbose_name='Дата и время добавления'),
        ),
    ]
