# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170921_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 21, 21, 10, 0, 496534), verbose_name='Дата и время добавления'),
        ),
    ]
