# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20171003_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 3, 21, 43, 13, 813486), verbose_name='Дата и время добавления'),
        ),
    ]
