# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170724_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 24, 17, 14, 52, 100068), verbose_name='Дата и время добавления'),
        ),
    ]
