# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя')),
                ('contact', models.TextField(verbose_name='Номер телефона или email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('worked', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name_plural': 'Обратная связь',
                'verbose_name': 'Обратная связь',
                'db_table': 'feedback',
            },
        ),
    ]
