# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soyzniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя')),
                ('contact', models.TextField(verbose_name='Номер телефона или email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('worked', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'feedback',
                'verbose_name': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('second_id', models.CharField(max_length=20, verbose_name='Значение хранимое у пользователя')),
                ('count_visits', models.BigIntegerField(max_length=20, verbose_name='Соличество посещений')),
                ('date_visit', models.DateField(verbose_name='Дата последнего посещения')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.Country', verbose_name='Страна нахождения')),
            ],
            options={
                'verbose_name_plural': 'Посетители',
                'db_table': 'visitors',
                'verbose_name': 'Посетитель',
            },
        ),
    ]
