# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='count_visits',
            field=models.BigIntegerField(max_length=20, verbose_name='Соличество посещений'),
        ),
    ]
