# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='worked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.TextField(verbose_name='Номер телефона или email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
    ]
