# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('soyzniki', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('unp_unn', models.IntegerField(verbose_name='УНП-УНН')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('thelephones', models.CharField(max_length=80, verbose_name='Телефоны организации')),
                ('email', models.EmailField(max_length=50, verbose_name='Email орнанизации')),
                ('street', models.CharField(max_length=254, verbose_name='Улица, дом')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.City', verbose_name='Город/Населенный пункт')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.Country', verbose_name='Страна')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.District', verbose_name='Район')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.Region', verbose_name='Область/Регион')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
                'verbose_name': 'Партнер',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Название услуги')),
                ('transport', models.IntegerField(choices=[(1, 'Все виды'), (2, 'Легковой'), (3, 'Грузовой')], default=1, verbose_name='Вид транспорта')),
                ('street', models.CharField(max_length=150, verbose_name='Улица, дом')),
                ('time_work', models.TextField(max_length=400, verbose_name='Время работы (хранится в json)')),
                ('thelephones', models.TextField(blank=True, max_length=800, null=True, verbose_name='Телефоны (не обязательное)')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url сайта (не обязательное)')),
                ('desc', models.TextField(max_length=800, verbose_name='Описание')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('stock', models.BooleanField(default=False, verbose_name='Наличие акции')),
                ('content_stock', models.TextField(blank=True, max_length=300, null=True, verbose_name='Текст акции')),
                ('other_services', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительные услуги (нe активно)')),
                ('active', models.BooleanField(default=True, verbose_name='Включить в поиск')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.City', verbose_name='Населенный пункт')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.Country', verbose_name='Страна')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.District', verbose_name='Район')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_related', to='partner.Partner', verbose_name='Кому принадлежит точка')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyzniki.Region', verbose_name='Область/регион')),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Services', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name_plural': 'Точки на карте',
                'verbose_name': 'Точка на карте',
                'db_table': 'points',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Название тарифного плана')),
                ('description', models.TextField(verbose_name='Описание тарифного плана')),
                ('cost', models.CharField(max_length=15, verbose_name='Стоимость тарифного плана')),
            ],
            options={
                'verbose_name_plural': 'Тарифные планы',
                'verbose_name': 'Тарифный план',
                'db_table': 'tariff',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Tariff', verbose_name='Тарифный план'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.ManyToManyField(related_name='users', to='user.User', verbose_name='Пользователь'),
        ),
    ]
